/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd;


public class App {

    public static void main(String[] args) {
        // Cria uma instância da classe externa
        App app = new App();
        
        // Cria uma instância da classe interna usando a instância da classe externa
        
    }
    
    
    public int somar(int a, int b) {
        return a + b;
    }
}
